///|
typealias @tokens.(Token, TokenKind)

///|
typealias @ast_types.(
  Location,
  Comment,
  CharLiteral,
  StringLiteral,
  InterpLiteral
)

///|
typealias @mbti_ast.(
  Name,
  QualifiedName,
  Visibility,
  Constant,
  Type,
  ErrorType,
  Parameter,
  TypeParamNoConstraints,
  TypeParamWithConstraints,
  TraitMethodParameter,
  FieldDecl,
  ConstrDecl,
  ConstrParam,
  AliasSig,
  TraitSig,
  TraitMethodSig,
  ImplSig,
  FuncSig,
  ValueSig,
  ConstSig,
  TypeSig,
  Sig,
  PackageImport,
  Mbti
)
