///|
pub extend RangeKind with Debug::{to_repr}

///|
pub extend Visibility with Debug::{to_repr}

///|
pub extend Constant with Debug::{to_repr}

///|
pub extend Label with Debug::{to_repr}

///|
pub extend ConstrName with Debug::{to_repr}

///|
pub extend LongIdent with Debug::{to_repr}

///|
pub extend TypeName with Debug::{to_repr}

///|
pub extend ConstrId with Debug::{to_repr}

///|
pub extend Type with Debug::{to_repr}

///|
pub extend ErrorType with Debug::{to_repr}

///|
pub extend ConstrParam with Debug::{to_repr}

///|
pub extend ConstrDecl with Debug::{to_repr}

///|
pub extend ExceptionDecl with Debug::{to_repr}

///|
pub extend FieldName with Debug::{to_repr}

///|
pub extend FieldDecl with Debug::{to_repr}

///|
pub extend TypeDesc with Debug::{to_repr}

///|
pub extend Hole with Debug::{to_repr}

///|
pub extend ArgumentKind with Debug::{to_repr}

///|
pub extend FnKind with Debug::{to_repr}

///|
pub extend Group with Debug::{to_repr}

///|
pub extend TrailingMark with Debug::{to_repr}

///|
pub extend TypeVarConstraint with Debug::{to_repr}

///|
pub extend TypeVarBinder with Debug::{to_repr}

///|
pub extend TypeDeclBinder with Debug::{to_repr}

///|
pub extend Binder with Debug::{to_repr}

///|
pub extend Var with Debug::{to_repr}

///|
pub extend ConstructorExtraInfo with Debug::{to_repr}

///|
pub extend Constructor with Debug::{to_repr}

///|
pub extend Accessor with Debug::{to_repr}

///|
pub extend AliasTarget with Debug::{to_repr}

///|
pub extend Argument with Debug::{to_repr}

///|
pub extend Parameter with Debug::{to_repr}

///|
pub extend Case with Debug::{to_repr}

///|
pub extend SpreadableElem with Debug::{to_repr}

///|
pub extend MapExprElem with Debug::{to_repr}

///|
pub extend StaticAssertion with Debug::{to_repr}

///|
pub extend Func with Debug::{to_repr}

///|
pub extend FieldDef with Debug::{to_repr}

///|
pub extend InterpElem with Debug::{to_repr}

///|
pub extend MultilineStringElem with Debug::{to_repr}

///|
pub extend LexPattern with Debug::{to_repr}

///|
pub extend LexTopPattern with Debug::{to_repr}

///|
pub extend LexCase with Debug::{to_repr}

///|
pub extend LexScanCase with Debug::{to_repr}

///|
pub extend RegexPattern with Debug::{to_repr}

///|
pub extend LexScanCasePattern with Debug::{to_repr}

///|
pub extend PredicateQuantifierKind with Debug::{to_repr}

///|
pub extend ListComprehensionKind with Debug::{to_repr}

///|
pub extend Expr with Debug::{to_repr}

///|
pub extend TryOperatorKind with Debug::{to_repr}

///|
pub extend DotDotBinder with Debug::{to_repr}

///|
pub extend ArrayPattern with Debug::{to_repr}

///|
pub extend ArrayPatterns with Debug::{to_repr}

///|
pub extend WhereClause with Debug::{to_repr}

///|
pub extend FieldPat with Debug::{to_repr}

///|
pub extend ConstrPatArg with Debug::{to_repr}

///|
pub extend MapPatElem with Debug::{to_repr}

///|
pub extend Pattern with Debug::{to_repr}

///|
pub extend DerivingDirective with Debug::{to_repr}

///|
pub extend TypeDecl with Debug::{to_repr}

///|
pub extend FuncStubs with Debug::{to_repr}

///|
pub extend EmbeddedCode with Debug::{to_repr}

///|
pub extend DeclBody with Debug::{to_repr}

///|
pub extend FunDecl with Debug::{to_repr}

///|
pub extend TraitMethodDecl with Debug::{to_repr}

///|
pub extend TraitDecl with Debug::{to_repr}

///|
pub extend UsingKind with Debug::{to_repr}

///|
pub extend ImportPackage with Debug::{to_repr}

///|
pub extend Impl with Debug::{to_repr}

///|
pub extend DocString with Debug::{to_repr}

///|
pub extend ArrowFnParam with Debug::{to_repr}
