///|
test "list" (t : @test.Test) {
  t.run("list")
}

///|
test "bytes" (t : @test.Test) {
  t.run("bytes")
}

///|
test "byte" (t : @test.Test) {
  t.run("byte")
}

///|
test "sorted_set" (t : @test.Test) {
  t.run("sorted_set")
}

///|
test "abort" (t : @test.Test) {
  t.run("abort")
}

///|
test "coverage" (t : @test.Test) {
  t.run("coverage")
}

///|
test "json" (t : @test.Test) {
  t.run("json")
}

///|
test "option" (t : @test.Test) {
  t.run("option")
}

///|
test "int" (t : @test.Test) {
  t.run("int")
}

///|
test "priority_queue" (t : @test.Test) {
  t.run("priority_queue")
}

///|
test "float" (t : @test.Test) {
  t.run("float")
}

///|
test "random_source" (t : @test.Test) {
  t.run("random_source")
}

///|
test "queue" (t : @test.Test) {
  t.run("queue")
}

///|
test "string" (t : @test.Test) {
  t.run("string")
}

///|
test "int64" (t : @test.Test) {
  t.run("int64")
}

///|
test "uint16" (t : @test.Test) {
  t.run("uint16")
}

///|
test "bigint" (t : @test.Test) {
  t.run("bigint")
}

///|
test "ref" (t : @test.Test) {
  t.run("ref")
}

///|
test "quickcheck" (t : @test.Test) {
  t.run("quickcheck")
}

///|
test "builtin" (t : @test.Test) {
  t.run("builtin")
}

///|
test "tuple" (t : @test.Test) {
  t.run("tuple")
}

///|
test "unit" (t : @test.Test) {
  t.run("unit")
}

///|
test "hashmap" (t : @test.Test) {
  t.run("hashmap")
}

///|
test "ryu" (t : @test.Test) {
  t.run("ryu")
}

///|
test "uint64" (t : @test.Test) {
  t.run("uint64")
}

///|
test "buffer" (t : @test.Test) {
  t.run("buffer")
}

///|
test "bool" (t : @test.Test) {
  t.run("bool")
}

///|
test "int16" (t : @test.Test) {
  t.run("int16")
}

///|
test "hashset" (t : @test.Test) {
  t.run("hashset")
}

///|
test "math" (t : @test.Test) {
  t.run("math")
}

///|
test "cmp" (t : @test.Test) {
  t.run("cmp")
}

///|
test "result" (t : @test.Test) {
  t.run("result")
}

///|
test "error" (t : @test.Test) {
  t.run("error")
}

///|
test "set" (t : @test.Test) {
  t.run("set")
}

///|
test "path" (t : @test.Test) {
  t.run("path")
}

///|
test "prelude" (t : @test.Test) {
  t.run("prelude")
}

///|
test "random" (t : @test.Test) {
  t.run("random")
}

///|
test "sparse_array" (t : @test.Test) {
  t.run("sparse_array")
}

///|
test "uint" (t : @test.Test) {
  t.run("uint")
}

///|
test "double" (t : @test.Test) {
  t.run("double")
}

///|
test "env" (t : @test.Test) {
  t.run("env")
}

///|
test "test" (t : @test.Test) {
  t.run("test")
}

///|
test "splitmix" (t : @test.Test) {
  t.run("splitmix")
}

///|
test "bench" (t : @test.Test) {
  t.run("bench")
}

///|
test "array" (t : @test.Test) {
  t.run("array")
}

///|
test "char" (t : @test.Test) {
  t.run("char")
}

///|
test "strconv" (t : @test.Test) {
  t.run("strconv")
}

///|
test "deque" (t : @test.Test) {
  t.run("deque")
}

///|
test "sorted_map" (t : @test.Test) {
  t.run("sorted_map")
}

///|
test "rational" (t : @test.Test) {
  t.run("rational")
}
