///|
test "no_trailing_newline_extern" (t : @test.T) {
  t.run("no_trailing_newline_extern")
}

///|
test "invalid_token" (t : @test.T) {
  t.run("invalid_token")
}

///|
test "iter_range" (t : @test.T) {
  t.run("iter_range")
}

///|
test "brace_grouped_ident" (t : @test.T) {
  t.run("brace_grouped_ident")
}

///|
test "continue_labeled_loop" (t : @test.T) {
  t.run("continue_labeled_loop")
}

///|
test "explicit_method" (t : @test.T) {
  t.run("explicit_method")
}

///|
test "postfix_label" (t : @test.T) {
  t.run("postfix_label")
}

///|
test "uminus" (t : @test.T) {
  t.run("uminus")
}

///|
test "colon_recovery" (t : @test.T) {
  t.run("colon_recovery")
}

///|
test "invalid_unicode" (t : @test.T) {
  t.run("invalid_unicode")
}

///|
test "record_pat_pun" (t : @test.T) {
  t.run("record_pat_pun")
}

///|
test "map_literal" (t : @test.T) {
  t.run("map_literal")
}

///|
test "abbreviation_let" (t : @test.T) {
  t.run("abbreviation_let")
}

///|
test "arrow_fn4" (t : @test.T) {
  t.run("arrow_fn4")
}

///|
test "attribute_name" (t : @test.T) {
  t.run("attribute_name")
}

///|
test "impl" (t : @test.T) {
  t.run("impl")
}

///|
test "question_optional_arg" (t : @test.T) {
  t.run("question_optional_arg")
}

///|
test "or_alias_pattern_prec" (t : @test.T) {
  t.run("or_alias_pattern_prec")
}

///|
test "tuple" (t : @test.T) {
  t.run("tuple")
}

///|
test "open_constr_pat" (t : @test.T) {
  t.run("open_constr_pat")
}

///|
test "async_fn" (t : @test.T) {
  t.run("async_fn")
}

///|
test "utf16_escape" (t : @test.T) {
  t.run("utf16_escape")
}

///|
test "tuples_err6" (t : @test.T) {
  t.run("tuples_err6")
}

///|
test "tuples_err7" (t : @test.T) {
  t.run("tuples_err7")
}

///|
test "tuples" (t : @test.T) {
  t.run("tuples")
}

///|
test "local_types" (t : @test.T) {
  t.run("local_types")
}

///|
test "recover_wrong_deliminator" (t : @test.T) {
  t.run("recover_wrong_deliminator")
}

///|
test "generic_fn" (t : @test.T) {
  t.run("generic_fn")
}

///|
test "extern_type" (t : @test.T) {
  t.run("extern_type")
}

///|
test "package3" (t : @test.T) {
  t.run("package3")
}

///|
test "package2" (t : @test.T) {
  t.run("package2")
}

///|
test "operator_bitwise_and" (t : @test.T) {
  t.run("operator_bitwise_and")
}

///|
test "const" (t : @test.T) {
  t.run("const")
}

///|
test "derive" (t : @test.T) {
  t.run("derive")
}

///|
test "trait_object" (t : @test.T) {
  t.run("trait_object")
}

///|
test "num_literal" (t : @test.T) {
  t.run("num_literal")
}

///|
test "bad_interp" (t : @test.T) {
  t.run("bad_interp")
}

///|
test "guard_if" (t : @test.T) {
  t.run("guard_if")
}

///|
test "super_trait" (t : @test.T) {
  t.run("super_trait")
}

///|
test "try_simple" (t : @test.T) {
  t.run("try_simple")
}

///|
test "semi_insertion" (t : @test.T) {
  t.run("semi_insertion")
}

///|
test "try_error" (t : @test.T) {
  t.run("try_error")
}

///|
test "no_trailing_newline_ffi1" (t : @test.T) {
  t.run("no_trailing_newline_ffi1")
}

///|
test "no_trailing_newline_let" (t : @test.T) {
  t.run("no_trailing_newline_let")
}

///|
test "try" (t : @test.T) {
  t.run("try")
}

///|
test "match_using" (t : @test.T) {
  t.run("match_using")
}

///|
test "ffi" (t : @test.T) {
  t.run("ffi")
}

///|
test "if_match_recovery" (t : @test.T) {
  t.run("if_match_recovery")
}

///|
test "invalid_error_type" (t : @test.T) {
  t.run("invalid_error_type")
}

///|
test "pub_test1" (t : @test.T) {
  t.run("pub_test1")
}

///|
test "pub_test0" (t : @test.T) {
  t.run("pub_test0")
}

///|
test "same_sync_multi_times" (t : @test.T) {
  t.run("same_sync_multi_times")
}

///|
test "semi_pattern_test" (t : @test.T) {
  t.run("semi_pattern_test")
}

///|
test "callback_test" (t : @test.T) {
  t.run("callback_test")
}

///|
test "explicit_record" (t : @test.T) {
  t.run("explicit_record")
}

///|
test "newtype" (t : @test.T) {
  t.run("newtype")
}

///|
test "array_rest_pat" (t : @test.T) {
  t.run("array_rest_pat")
}

///|
test "record_punning" (t : @test.T) {
  t.run("record_punning")
}

///|
test "fnalias" (t : @test.T) {
  t.run("fnalias")
}

///|
test "array2" (t : @test.T) {
  t.run("array2")
}

///|
test "arrow_fn" (t : @test.T) {
  t.run("arrow_fn")
}

///|
test "error_type" (t : @test.T) {
  t.run("error_type")
}

///|
test "bad_recovery" (t : @test.T) {
  t.run("bad_recovery")
}

///|
test "cfg_test_main_init" (t : @test.T) {
  t.run("cfg_test_main_init")
}

///|
test "for_else" (t : @test.T) {
  t.run("for_else")
}

///|
test "string_escape_error" (t : @test.T) {
  t.run("string_escape_error")
}

///|
test "docstring" (t : @test.T) {
  t.run("docstring")
}

///|
test "augmented" (t : @test.T) {
  t.run("augmented")
}

///|
test "get_set" (t : @test.T) {
  t.run("get_set")
}

///|
test "no_trailing_newline_type" (t : @test.T) {
  t.run("no_trailing_newline_type")
}

///|
test "no_trailing_newline_fn" (t : @test.T) {
  t.run("no_trailing_newline_fn")
}

///|
test "for" (t : @test.T) {
  t.run("for")
}

///|
test "while" (t : @test.T) {
  t.run("while")
}

///|
test "fnname_bang" (t : @test.T) {
  t.run("fnname_bang")
}

///|
test "try_with_parentheses" (t : @test.T) {
  t.run("try_with_parentheses")
}

///|
test "operator_bitwise_or" (t : @test.T) {
  t.run("operator_bitwise_or")
}

///|
test "unicode_test" (t : @test.T) {
  t.run("unicode_test")
}

///|
test "local_types_error" (t : @test.T) {
  t.run("local_types_error")
}

///|
test "trait_obj_fn_apply" (t : @test.T) {
  t.run("trait_obj_fn_apply")
}

///|
test "array_spread" (t : @test.T) {
  t.run("array_spread")
}

///|
test "letrec_err" (t : @test.T) {
  t.run("letrec_err")
}

///|
test "foreign_constr" (t : @test.T) {
  t.run("foreign_constr")
}

///|
test "fn_exclamation" (t : @test.T) {
  t.run("fn_exclamation")
}

///|
test "allow_trailing_comma" (t : @test.T) {
  t.run("allow_trailing_comma")
}

///|
test "default_impl" (t : @test.T) {
  t.run("default_impl")
}

///|
test "tuples_err1" (t : @test.T) {
  t.run("tuples_err1")
}

///|
test "enum_custom_tag" (t : @test.T) {
  t.run("enum_custom_tag")
}

///|
test "optional_type_abbrv" (t : @test.T) {
  t.run("optional_type_abbrv")
}

///|
test "no_trailing_newline_enum" (t : @test.T) {
  t.run("no_trailing_newline_enum")
}

///|
test "unfinished_string" (t : @test.T) {
  t.run("unfinished_string")
}

///|
test "package4" (t : @test.T) {
  t.run("package4")
}

///|
test "pipe" (t : @test.T) {
  t.run("pipe")
}

///|
test "type_alias" (t : @test.T) {
  t.run("type_alias")
}

///|
test "match_match" (t : @test.T) {
  t.run("match_match")
}

///|
test "no_trailing_newline_ffi2" (t : @test.T) {
  t.run("no_trailing_newline_ffi2")
}

///|
test "constrained_type_param" (t : @test.T) {
  t.run("constrained_type_param")
}

///|
test "no_trailing_newline_struct" (t : @test.T) {
  t.run("no_trailing_newline_struct")
}

///|
test "tuples_err10" (t : @test.T) {
  t.run("tuples_err10")
}

///|
test "match_arm" (t : @test.T) {
  t.run("match_arm")
}

///|
test "uplus" (t : @test.T) {
  t.run("uplus")
}

///|
test "string_pattern" (t : @test.T) {
  t.run("string_pattern")
}

///|
test "loop" (t : @test.T) {
  t.run("loop")
}

///|
test "operator_bitwise_xor" (t : @test.T) {
  t.run("operator_bitwise_xor")
}

///|
test "byte_literal_in_parens" (t : @test.T) {
  t.run("byte_literal_in_parens")
}

///|
test "async_lambda" (t : @test.T) {
  t.run("async_lambda")
}

///|
test "escape" (t : @test.T) {
  t.run("escape")
}

///|
test "pub_test2" (t : @test.T) {
  t.run("pub_test2")
}

///|
test "pub_test3" (t : @test.T) {
  t.run("pub_test3")
}

///|
test "derive_arguments" (t : @test.T) {
  t.run("derive_arguments")
}

///|
test "get_slice" (t : @test.T) {
  t.run("get_slice")
}

///|
test "async_type" (t : @test.T) {
  t.run("async_type")
}

///|
test "error_recovery" (t : @test.T) {
  t.run("error_recovery")
}

///|
test "gitlab_issue_1612" (t : @test.T) {
  t.run("gitlab_issue_1612")
}

///|
test "pattern_guard" (t : @test.T) {
  t.run("pattern_guard")
}

///|
test "is_expr" (t : @test.T) {
  t.run("is_expr")
}

///|
test "local_types3" (t : @test.T) {
  t.run("local_types3")
}

///|
test "local_types2" (t : @test.T) {
  t.run("local_types2")
}

///|
test "enumview" (t : @test.T) {
  t.run("enumview")
}

///|
test "map_pattern" (t : @test.T) {
  t.run("map_pattern")
}

///|
test "fn_arguments" (t : @test.T) {
  t.run("fn_arguments")
}

///|
test "tuples_err5" (t : @test.T) {
  t.run("tuples_err5")
}

///|
test "partial_type_error" (t : @test.T) {
  t.run("partial_type_error")
}

///|
test "tuples_err4" (t : @test.T) {
  t.run("tuples_err4")
}

///|
test "fn_exp_test" (t : @test.T) {
  t.run("fn_exp_test")
}

///|
test "trait" (t : @test.T) {
  t.run("trait")
}

///|
test "trait_lint" (t : @test.T) {
  t.run("trait_lint")
}

///|
test "package1" (t : @test.T) {
  t.run("package1")
}

///|
test "multiline_string_literals" (t : @test.T) {
  t.run("multiline_string_literals")
}

///|
test "return" (t : @test.T) {
  t.run("return")
}

///|
test "not_syntax" (t : @test.T) {
  t.run("not_syntax")
}

///|
test "foreach" (t : @test.T) {
  t.run("foreach")
}

///|
test "type_exclamation" (t : @test.T) {
  t.run("type_exclamation")
}

///|
test "bytes_literal" (t : @test.T) {
  t.run("bytes_literal")
}

///|
test "try_question" (t : @test.T) {
  t.run("try_question")
}

///|
test "array_pat_trailing_comma" (t : @test.T) {
  t.run("array_pat_trailing_comma")
}

///|
test "relaxed_for" (t : @test.T) {
  t.run("relaxed_for")
}

///|
test "toplevel_test" (t : @test.T) {
  t.run("toplevel_test")
}

///|
test "struct_spread" (t : @test.T) {
  t.run("struct_spread")
}

///|
test "pattern_tuple" (t : @test.T) {
  t.run("pattern_tuple")
}

///|
test "constr_unit" (t : @test.T) {
  t.run("constr_unit")
}

///|
test "arrow_fn_error" (t : @test.T) {
  t.run("arrow_fn_error")
}

///|
test "local_docs" (t : @test.T) {
  t.run("local_docs")
}

///|
test "allow_if_match_in_opr" (t : @test.T) {
  t.run("allow_if_match_in_opr")
}

///|
test "invalid_expr_in_condition" (t : @test.T) {
  t.run("invalid_expr_in_condition")
}

///|
test "labelled_arg" (t : @test.T) {
  t.run("labelled_arg")
}

///|
test "field_vs_method" (t : @test.T) {
  t.run("field_vs_method")
}

///|
test "tuples_err2" (t : @test.T) {
  t.run("tuples_err2")
}

///|
test "tuples_err3" (t : @test.T) {
  t.run("tuples_err3")
}

///|
test "attribute" (t : @test.T) {
  t.run("attribute")
}

///|
test "main_fn_with_return_unit" (t : @test.T) {
  t.run("main_fn_with_return_unit")
}

///|
test "text_segment_test" (t : @test.T) {
  t.run("text_segment_test")
}

///|
test "hello" (t : @test.T) {
  t.run("hello")
}

///|
test "defer" (t : @test.T) {
  t.run("defer")
}

///|
test "uint_literal" (t : @test.T) {
  t.run("uint_literal")
}

///|
test "float_crlf" (t : @test.T) {
  t.run("float_crlf")
}

///|
test "fun_binder" (t : @test.T) {
  t.run("fun_binder")
}

///|
test "failed_error_recover" (t : @test.T) {
  t.run("failed_error_recover")
}

///|
test "tuples_err8" (t : @test.T) {
  t.run("tuples_err8")
}

///|
test "tuples_err9" (t : @test.T) {
  t.run("tuples_err9")
}

///|
test "package" (t : @test.T) {
  t.run("package")
}

///|
test "interp_test" (t : @test.T) {
  t.run("interp_test")
}

///|
test "function_type_with_trailing_comma" (t : @test.T) {
  t.run("function_type_with_trailing_comma")
}

///|
test "guard_error" (t : @test.T) {
  t.run("guard_error")
}

///|
test "catch_all" (t : @test.T) {
  t.run("catch_all")
}

///|
test "missing_type_after_thin_arrow" (t : @test.T) {
  t.run("missing_type_after_thin_arrow")
}

///|
test "recand" (t : @test.T) {
  t.run("recand")
}

///|
test "array_spread2" (t : @test.T) {
  t.run("array_spread2")
}

///|
test "cascade" (t : @test.T) {
  t.run("cascade")
}

///|
test "while_else" (t : @test.T) {
  t.run("while_else")
}

///|
test "constr_mut_field" (t : @test.T) {
  t.run("constr_mut_field")
}

///|
test "tuple_multiline_str" (t : @test.T) {
  t.run("tuple_multiline_str")
}

///|
test "path_pattern_test" (t : @test.T) {
  t.run("path_pattern_test")
}

///|
test "parse_float32_literal" (t : @test.T) {
  t.run("parse_float32_literal")
}

///|
test "trait_method_param_name" (t : @test.T) {
  t.run("trait_method_param_name")
}

///|
test "negative_literal_pattern" (t : @test.T) {
  t.run("negative_literal_pattern")
}

///|
test "invalid_trait_def" (t : @test.T) {
  t.run("invalid_trait_def")
}

///|
test "pub_test5" (t : @test.T) {
  t.run("pub_test5")
}

///|
test "list_example" (t : @test.T) {
  t.run("list_example")
}

///|
test "pub_test4" (t : @test.T) {
  t.run("pub_test4")
}

///|
test "record_punning_fail" (t : @test.T) {
  t.run("record_punning_fail")
}

///|
test "range_pattern" (t : @test.T) {
  t.run("range_pattern")
}

///|
test "docstring2" (t : @test.T) {
  t.run("docstring2")
}

///|
test "nested_exp" (t : @test.T) {
  t.run("nested_exp")
}

///|
test "error_polymorphism" (t : @test.T) {
  t.run("error_polymorphism")
}

///|
test "local_attrs" (t : @test.T) {
  t.run("local_attrs")
}

///|
test "underscore_test" (t : @test.T) {
  t.run("underscore_test")
}

///|
test "invalid_type" (t : @test.T) {
  t.run("invalid_type")
}

///|
test "let_mut" (t : @test.T) {
  t.run("let_mut")
}

///|
test "try_exclamation" (t : @test.T) {
  t.run("try_exclamation")
}
