///|
pub extend Name with Debug::{to_repr}

///|
pub extend Name with ToJson::{to_json}

///|
pub extend QualifiedName with Debug::{to_repr}

///|
pub extend TypeParamWithConstraints with Debug::{to_repr}

///|
pub extend TypeParamNoConstraints with Debug::{to_repr}

///|
pub extend MethodSelfType with Debug::{to_repr}

///|
pub extend FuncSig with Debug::{to_repr}

///|
pub extend TypeDefinition with Debug::{to_repr}

///|
pub extend TypeSig with Debug::{to_repr}

///|
pub extend AliasSig with Debug::{to_repr}

///|
pub extend TraitMethodSig with Debug::{to_repr}

///|
pub extend TraitSig with Debug::{to_repr}

///|
pub extend ImplSig with Debug::{to_repr}

///|
pub extend ConstSig with Debug::{to_repr}

///|
pub extend ValueSig with Debug::{to_repr}

///|
pub extend PackageImport with Debug::{to_repr}

///|
pub extend Sig with Debug::{to_repr}

///|
pub extend Mbti with Debug::{to_repr}
